.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH DAISY 2 "OCTOBER 2009" Linux "User Manuals"
.SH NAME
daisy-js \- Daisy Javascripter
.SH SYNOPSIS
.B daisy-js 
\<js-file\>
.SH DESCRIPTION
The
.B daisy-js
script calls Rhino, a Java-based Javascript implementation.  This makes it easy to use the Java API of the repository server to automate all kinds of operations. In other words: easy scripting of the repository server. It brings all the benefits of Daisy's high-level repository API without requiring Java knowledge or the setup of a development environment.
.SH ENVIRONMENT
.IP DAISY_HOME
Directory where Daisy is installed.  If not specified /usr/lib/daisy is assumed.
.SH SEE ALSO
For more information and examples go to the daisy documentation site : 
 http://docs.outerthought.org/daisydocs-2_4

Daisy Javascripting specific information can be found here :
 http://docs.outerthought.org/daisy-docs-2_4/373-daisy/375-daisy/153-daisy.html
.SH AUTHOR
Outerthought <info at outerthought dot org>
